apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service  # Nom de votre service MySQL
spec:
  ports:
    - protocol: TCP
      port: 3306  # Port utilisé par MySQL
  selector:
    app: zen_shtern # Étiquette du pod de votre base de données MySQL
