apiVersion: v1
kind: Service
metadata:
  name: thibault-flask-service
spec:
  selector:
    app: thibault_flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Modification du type de service en LoadBalancer
