apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: thibault-mon-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thibault_flask
  template:
    metadata:
      labels:
        app: thibault_flask
    spec:
      containers:
      - name: thibault-flask-container
        image: tplulu/projet_kub:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thibault-mysql-db-service
spec:
  replicas: 1  # Vous pouvez ajuster le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: thibault-mysql-db-service
  template:
    metadata:
      labels:
        app: thibault-mysql-db-service
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306  # Port utilisé par MySQL
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password  # Remplacez par le mot de passe souhaité
        - name: MYSQL_DATABASE
          value: test  # Nom de la base de données par défaut
