apiVersion: apps/v1
kind: Deployment
metadata:
  name: thibault-flask-deployment
  labels:
    app: thibault-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thibault_flask
  template:
    metadata:
      labels:
        app: thibault_flask
    spec:
      containers:
      - name: thibault-flask-container
        image: tplulu/projet_kub:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thibault-mysql-db-service
spec:
  replicas: 1  # Vous pouvez ajuster le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: thibault-mysql-db-service
  template:
    metadata:
      labels:
        app: thibault-mysql-db-service
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306  # Port utilisé par MySQL
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password  # Remplacez par le mot de passe souhaité
        - name: MYSQL_DATABASE
          value: test  # Nom de la base de données par défaut
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE IF NOT EXISTS user (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
