name: GitHub Actions Demo
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Azure Login
        run: |
          az login --username ${{ secrets.AZUR_EMAIL }} --password ${{ secrets.AZUR_PASSWORD }}
          az account set --subscription d18efcbe-caa9-4004-ac2c-7312261e11de
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      - name: Deploy to Kubernetes
        run: |
          kubectl delete deployment thibault-flask-deployment || echo 'already deleted'
          kubectl apply -f thibault_deployment.yaml --validate=false
          kubectl apply -f thibault_service_bdd.yaml --validate=false
          kubectl apply -f thibault_service_loadbalancer.yaml --validate=false
       